[package]
description = "Dummy"
license = "MIT"
edition = "2021"
name = "hc_zome_dummy_integrity"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "hc_zome_dummy_integrity"

[dependencies]
derive_more = "0"
serde = "1"

hdi = "0.0.14"